<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $block->getData('outputHelper');
?>
<!--qty Box start -->
<?php $qtyupdateBlock =  $this->getLayout()->createBlock("Citytech\Customization\Block\Cart\Qtyupdate"); ?>
<!--qty Box end -->
<?php 
$productattributeblock = $block->getLayout()->createBlock('Citytech\Categoryattributes\Block\Productattribute');
?>

<?php $helperCustomization = $this->helper("Citytech\Customization\Helper\Customization"); ?> 
<?php if(   $helperCustomization->getCurrentControllerName() == "category" && 
            $helperCustomization->getCurrentActionName() == "view" && 
            $helperCustomization->getCurrentRouteName() == "catalog"        
        ){ ?>
    <?php $categoryViewBlock =  $this->getLayout()->createBlock("Magento\Catalog\Block\Category\View"); ?>
    <?php if ($_description = $categoryViewBlock->getCurrentCategory()->getDescription()) :?>
        <div class="category-view-description">
            <?= /* @noEscape */ $this->helper(Magento\Catalog\Helper\Output::class)->categoryAttribute(
                $categoryViewBlock->getCurrentCategory(),
                $_description,
                'description'
            ) ?>
        </div>
    <?php endif; ?>
<?php } ?>

  
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() === 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
	<?php $cat_search = $this->getRequest()->getParam('cq'); ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
			
            <?php foreach ($_productCollection as $_product): ?>			
			<?php
			$cart_qty = 0;
			$item_id = 0;
			?>
			<li class="item product product-item">
			<?php
				if(isset($cat_search) && !empty($cat_search)){
					if (strpos(strtolower($_product->getName()), strtolower($cat_search)) === false){
						continue;
					}
				}
			?>
			<?php $product_id = $_product->getId();?>
			
			<?php
				$IdDoProduto = $_product->getId();
				$sku = $_product->getSku();


				$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
				 $cart = $objectManager->get('\Magento\Checkout\Model\Session'); 

				// retrieve quote items collection
				$itemsCollection = $cart->getQuote()->getItemsCollection();

				// get array of all items what can be display directly
				$itemsVisible = $cart->getQuote()->getAllVisibleItems();

				// retrieve quote items array
				 $items = $cart->getQuote()->getAllItems();
                //print_r($items);
				foreach($items as $item) {
					
					 if($IdDoProduto == $item->getProduct_id()){
						 
							$cart_qty = $item->getQty();
							$item_id = $item->getId();
					 }         
				  }
				  
				  //echo $cart_qty."-".$item_id;
				 ?>
			
			
            
                <div class="product-item-info"
                     id="product-item-info_<?= /* @noEscape */ $_product->getId() ?>"
                     data-container="product-<?= /* @noEscape */ $viewMode ?>">
                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = 'left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;';
                    }
                    ?>
					
					<?php 
						// Show product as New tag
						$nowdatetime = strtotime(date("d-m-Y"));
						$FromDate_strtotime = 0;
						$ToDate_strtotime = 0;
						
						$newFromDate = $_product->getNewsFromDate();
						$newToDate = $_product->getNewsToDate();
						if($newFromDate){
							$FromDateCreate = date_create($newFromDate);
							$FromDateChangeFormat = date_format($FromDateCreate,"d-m-Y");
							$FromDate_strtotime = strtotime(date($FromDateChangeFormat));
						}
						
						if($newToDate){
							$ToDateCreate = date_create($newToDate);
							$ToDateChangeFormat = date_format($ToDateCreate,"d-m-Y");
							$ToDate_strtotime = strtotime(date($ToDateChangeFormat));
						}

						if($FromDate_strtotime > 0 && $FromDate_strtotime <= $nowdatetime){
							$newProduct = 1;
						} elseif($ToDate_strtotime > 0 && $ToDate_strtotime >= $nowdatetime){
							$newProduct = 1;
						} else {
							$newProduct = 0;
						}
						
						if($newProduct == 1){
							?>
								<div class="prod_new"><?php echo __('New'); ?></div>
							<?php
						}	
					?>
					
                    <?php // Product Image ?>
                    <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                       class="product photo product-item-photo"
                       tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                <?=/* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name')?>
                            </a>
                        </strong>
						<div class="prod_reviews_summary_area">	
							<?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
						</div>

						<div class="prod_default_size">	
							<?php
								$DefaultSize = $productattributeblock->getProductDefaultSize($_product->getId());
								echo $DefaultSize;							 
							?>
						</div>
						
						<div class="prod_price_area">
							<div class="prod_price_amt">
								<?= /* @noEscape */ $block->getProductPrice($_product) ?>
							</div>
							<div class="prod_price_vat">
							<?php echo __('(Inc. VAT)'); ?>
							</div>
						</div>

                        <?= $block->getProductDetailsHtml($_product) ?>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions">
                                <div class="actions-primary">
                                    <?php if ($_product->isSaleable()):?>
										<?php $cartqty = 0; if ($_product->isAvailable()){ $cartqty = 1; } ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form"
                                              data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>"
                                              action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                                              method="post">
                                            <?php $optionsData = $block->getData('viewModel')->getOptionsData($_product); ?>
                                            <?php foreach ($optionsData as $optionItem): ?>
                                                <input type="hidden"
                                                       name="<?= $escaper->escapeHtml($optionItem['name']) ?>"
                                                       value="<?= $escaper->escapeHtml($optionItem['value']) ?>">
                                            <?php endforeach; ?>
                                            <input type="hidden"
                                                   name="product"
                                                   value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                            <input type="hidden"
                                                   name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                   value="<?=
                                                   /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED]
                                                    ?>">
                                            <?= $block->getBlockHtml('formkey') ?>

                                            <div class="qty-box" style="display:none">
                                                <a href="javascript:void(0)" class="qtyminus"><i class="fa fa-minus"></i></a>
												<input type="text" name="qty" id="qty<?php echo $_product->getId(); ?>" maxlength="4" min="1" value="<?= $cartqty * 1 ?>" title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty cart-item-qty" data-validate="<?= $block->escapeHtmlAttr(json_encode($block->getQuantityValidators())) ?>"/>
                                                <a href="javascript:void(0)" class="qtyplus"><i class="fa fa-plus"></i></a>
                                            </div>
                                            
                                                          
                                            <!--qty Box start -->              
                                            <div class="associated-product-qty-box-wrapper">
                                                <?php $_product         = $_product; // section product ?> 
                                                <?php $product_id       = $_product->getId();?>
                                                <?php $itemQtyInCart    = $qtyupdateBlock->getItemQty($product_id); ?>
                                                <?php $productType    = $qtyupdateBlock->getProductType($_product); ?>
                                                <?php //if($productType == "simple"){ ?>
                                                    <div id="qty_box_counter_<?php echo $product_id; ?>" class="qty-box-counter <?= $itemQtyInCart > 0 ? "has-product" : "" ?>">
                                                        <?= $itemQtyInCart > 0  ? $itemQtyInCart : "+" ?>
                                                    </div>
                                                <?php /* }else{ ?>
                                                    <div class="qty-box-counter-not-simple">
                                                        <a href="<?= $_product->getProductUrl(); ?>">
                                                            <?= "+" ?>
                                                        </a>
                                                    </div>
                                                <?php } */  ?> 
                                                <div class="associated-product-qty" style="display:none;"> 
                                                    <?php 
                                                        $deleteCLsQty ="";
                                                        if($itemQtyInCart ==1){
                                                            $deleteCLsQty = "delete-qty-minus";
                                                        }
                                                    ?>
                                                    <span 
                                                        id="associated_product_qty_minus_id_<?php echo $product_id; ?>"
                                                        class="associated-product-qty-minus <?= $deleteCLsQty; ?>" 
                                                        product_id="<?php echo $product_id; ?>" 
                                                    >-</span> 
                                                    <span>
                                                        <input name="quantity[<?php echo $product_id; ?>]" 
                                                               id="<?= "quantity_".$product_id; ?>"
                                                               type="number" 
                                                               class="associated-product-qty-input" 
                                                               value="<?= $itemQtyInCart; ?>"               
                                                               product_id="<?php echo $product_id; ?>"      
                                                        >
                                                    </span>
                                                    <span class="associated-product-qty-plus" 
                                                          product_id="<?php echo $product_id; ?>" 
                                                    >+ </span>
                                                </div>
                                            </div> 
                                            <!--qty Box End -->
                                            
                                            
                                        </form>					
                                    <?php else:?>
                                        <?php if ($_product->isAvailable()):?>
                                            <div class="stock available">
                                                <span><?= $escaper->escapeHtml(__('In stock')) ?></span></div>
                                        <?php else:?>
                                            <div class="stock unavailable">
                                                <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <?= strpos($pos, $viewMode . '-primary') ?
                                    /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                        $position,
                                        'product-item-info_' . $_product->getId() . ' div.actions-primary'
                                    ) : '' ?>
                                <div data-role="add-to-links" class="actions-secondary">
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                                <?= strpos($pos, $viewMode . '-secondary') ?
                                    /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                        $position,
                                        'product-item-info_' . $_product->getId() . ' div.actions-secondary'
                                    ) : '' ?>
                            </div>
                            <?php if ($showDescription): ?>
                                <div class="product description product-item-description">
                                    <?= /* @noEscape */ $_helper->productAttribute(
                                        $_product,
                                        $_product->getShortDescription(),
                                        'short_description'
                                    ) ?>
                                    <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                                       title="<?= /* @noEscape */ $_productNameStripped ?>"
                                       class="action more"><?= $escaper->escapeHtml(__('Learn More')) ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <?= strpos($pos, $viewMode . '-actions') ?
                /* @noEscape */ $secureRenderer->renderStyleAsTag(
                    $position,
                    'product-item-info_' . $_product->getId() . ' div.product-item-actions'
                ) : '' ?>
            </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
    <script type="text/x-magento-init">
    {
        "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {
                "product_sku": "<?= $escaper->escapeJs($_product->getSku()) ?>"
            }
        }
    }
    </script>
    

    
    <!--qty Box start -->
    <script>
        require([
            "jquery", 'jquery/ui'
        ], function ($) {

            $( ".associated-product-qty-plus").click(function() {
                var inputValAssociated = $(this).parent().find('.associated-product-qty-input').val();  

                if(inputValAssociated !== '0'){
                    var inputValAssociatedAdd = parseInt(inputValAssociated) + 1;
                }else{
                    var inputValAssociatedAdd = 1;
                }  

                var product_id      = $(this).attr("product_id");
                //$(this).parent().find('.associated-product-qty-input').val(inputValAssociatedAdd);
                var url = "<?= $block->escapeUrl($qtyupdateBlock->getAjaxAddActionUrl()) ?>";
                jQuery("body").loader("show");
                $.ajax({
                    type: "POST",
                    url: url,
                    data: {mode :"add" ,product_id : product_id, qty : 1 }, // serializes the form's elements.
                    success: function (data)
                    {
                        jQuery("body").loader("hide");
                        if(data.status_code ==1){                          
                            qtyBoxCounterUpdate(product_id,inputValAssociatedAdd);
                        }                  
                    }
                });  
            });
            
            $(".associated-product-qty-minus").click(function() {
                var inputValAssociated = parseInt($(this).parent().find('.associated-product-qty-input').val());              
                if(inputValAssociated > 0 ){
                    var inputValAssociatedAdd = inputValAssociated - 1;
                }else{
                    var inputValAssociatedAdd = 0;
                }
                //$(this).parent().find('.associated-product-qty-input').val(inputValAssociatedAdd);
                var product_id      = $(this).attr("product_id");

                var url = "<?= $block->escapeUrl($qtyupdateBlock->getAjaxUpdateActionUrl()) ?>";
                jQuery("body").loader("show");
                $.ajax({
                    type: "POST",
                    url: url,
                    data: {mode :"update", product_id : product_id, qty : inputValAssociatedAdd}, // serializes the form's elements.
                    success: function (data)
                    {
                        jQuery("body").loader("hide");
                        if(data.status_code ==1){
                            qtyBoxCounterUpdate(product_id,inputValAssociatedAdd);
                        }

                    }
                });  
            });

            $(".associated-product-qty-input").keyup(function() {
                var key = event.keyCode || event.charCode;

                if( key == 8 || key == 46 ){
                    return false;
                }            
                var inputValAssociated = parseInt($(this).val());     

                if(inputValAssociated > 0 ){
                    var inputValAssociatedAdd = inputValAssociated;
                    
                }else{
                    var inputValAssociatedAdd = 0;
                }

                var product_id      = $(this).attr("product_id");           
                var url = "<?= $block->escapeUrl($qtyupdateBlock->getAjaxUpdateActionUrl()) ?>";
                jQuery("body").loader("show");
                $.ajax({
                    type: "POST",
                    url: url,
                    data: {mode :"update", product_id : product_id, qty : inputValAssociatedAdd}, // serializes the form's elements.
                    success: function (data)
                    {
                        jQuery("body").loader("hide");
                        if(data.status_code ==1){
                            qtyBoxCounterUpdate(product_id,inputValAssociatedAdd);

                        }
                    }
                });  
            });

            $(document).on("blur", '.associated-product-qty-input', function() { 
                var inputValAssociated = $(this).val(); 
                if(!inputValAssociated){
                    $(this).val(0); 
                }
            });


            $(".qty-box-counter").click(function() {
                $(this).fadeOut();    
                $(this).next().fadeIn();
                $(this).next().delay(8000).fadeOut();           
                //$(this).stop(true,true).delay(8000).fadeOut();           
                $(this).delay(8000).fadeIn();     
                var has_product = $(this).hasClass("has-product");

                if(!has_product){
                    var inputQty = $(this).next().find('.associated-product-qty-input');
                    var inputValAssociated = inputQty.val(); 

                    if(inputValAssociated !== '0'){
                        var inputValAssociatedAdd = parseInt(inputValAssociated) + 1;
                    }else{
                        var inputValAssociatedAdd = 1;
                    }

                    var inputValAssociatedAdd = 1;
                    var product_id      = inputQty.attr("product_id");

                    //inputQty.val(inputValAssociatedAdd);
                    var url = "<?= $block->escapeUrl($qtyupdateBlock->getAjaxAddActionUrl()) ?>";
                    jQuery("body").loader("show");
                    $.ajax({
                        type: "POST",
                        url: url,
                        data: {mode :"add" ,product_id : product_id, qty : 1}, // serializes the form's elements.
                        success: function (data)
                        {
                            jQuery("body").loader("hide");
                            if(data.status_code ==1){                     
                                qtyBoxCounterUpdate(product_id,inputValAssociatedAdd);
                            }               
                        }

                    });    
                }
            });

           function qtyBoxCounterUpdate(product_id,inputValAssociatedAdd){
                var qty_box_counter_Id = "#qty_box_counter_"+product_id; 
                $("#quantity_"+product_id).val(inputValAssociatedAdd); 
                
                if(inputValAssociatedAdd > 0){
                    $(qty_box_counter_Id).text(inputValAssociatedAdd); 
                    $(qty_box_counter_Id).addClass("has-product"); 
                }else{
                    $(qty_box_counter_Id).text("+"); 
                    $(qty_box_counter_Id).removeClass("has-product");
                }

                if(inputValAssociatedAdd == 1){
                    $("#associated_product_qty_minus_id_"+product_id).addClass("delete-qty-minus"); 
                }else{
                    $("#associated_product_qty_minus_id_"+product_id).removeClass("delete-qty-minus");
                }
            }

        });
    </script>  
    <!--qty Box end -->
  
<?php endif; ?>



