<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Review\Block\Product\ReviewRenderer $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

$url = $block->getReviewsUrl() . '#reviews';
$urlForm = $block->getReviewsUrl() . '#review-form';
?>
<?php if ($block->isReviewEnabled() && $block->getReviewsCount()): ?>
    <?php $rating = $block->getRatingSummary(); ?>
    <div class="product-reviews-summary<?= !$rating ? ' no-rating' : '' ?>" itemprop="aggregateRating" itemscope
         itemtype="http://schema.org/AggregateRating">
        <?php if ($rating):?>
        <div class="rating-summary">
             <span class="label"><span><?= $block->escapeHtml(__('Rating')) ?>:</span></span>
			 <span class="rt"><?= $block->escapeHtmlAttr($rating)/20; ?> </span>
             <div class="rating-result" title="<?= $block->escapeHtmlAttr($rating); ?>%">
                 <span>
                     <span>
                         <span itemprop="ratingValue"><?= $block->escapeHtml($rating); ?>
                         </span>% of <span itemprop="bestRating">100</span>
                     </span>
                 </span>
             </div>
         </div>
            <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
                "width:" . $block->escapeHtmlAttr($rating) . "%",
                'div.rating-summary div.rating-result>span:first-child'
            ) ?>
        <?php endif;?>
        <div class="reviews-actions">
            <a class="action view"
               href="<?= $block->escapeUrl($url) ?>">
                <span itemprop="reviewCount"><?= $block->escapeHtml($block->getReviewsCount()) ?></span>&nbsp;
                <span><?= ($block->getReviewsCount() == 1) ? $block->escapeHtml(__('Review')) :
                        $block->escapeHtml(__('Ratings & Reviews')) ?>
                </span>
            </a>
            <!--<a class="action add" href="<?= $block->escapeUrl($urlForm) ?>">
                <?= $block->escapeHtml(__('Add Your Review')) ?>
            </a> -->
        </div>
    </div>
<?php elseif ($block->isReviewEnabled() && $block->getDisplayIfEmpty()): ?>
    <div class="product-reviews-summary empty">
        <div class="reviews-actions">
			
					<?php
					$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
					$customerSession = $objectManager->get('Magento\Customer\Model\Session');
					if($customerSession->isLoggedIn()) {
					   // customer login action
					?>
						<div id="button1" class="button">
							<span><?= $block->escapeHtml(__('Be the first to review this product')) ?></span>
						</div>						
				    <?php }else{ ?>	
					<a href="#social-login-popup" class="social-login-btn" data-effect="mfp-zoom-out">Be the first to review this product</a>
					<?php
					}
					?>							
			
			
			
        </div>
    </div>
<?php endif; ?>
