<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?= $block->escapeHtml(__('Sort By')) ?></label>
    <select id="sorter" data-role="sorter" class="sorter-options">
        <?php /* foreach ($block->getAvailableOrders() as $_key => $_order) :?>
            <option value="<?= $block->escapeHtmlAttr($_key) ?>"
                <?php if ($block->isOrderCurrent($_key)) :?>
                    selected="selected"
                <?php endif; ?>
                >
                <?= $block->escapeHtml(__($_order)) ?>
            </option>
        <?php endforeach; */?>
		<option value="<?php echo __('mostviewed&product_list_dir=desc'); ?>" <?php if ($block->isOrderCurrent('mostviewed')) :?>
                    selected="selected"
                <?php endif; ?> ><?php echo __('Popularity'); ?></option>
		<option value="<?php echo __('price&product_list_dir=desc'); ?>"
			<?php if ($block->isOrderCurrent('price') && $block->getCurrentDirection() == 'desc') :?>
                    selected="selected"
                <?php endif; ?> ><?php echo __('Price (High - Low)'); ?></option>
		<option value="<?php echo __('price&product_list_dir=asc'); ?>" 
			<?php if ($block->isOrderCurrent('price') && $block->getCurrentDirection() == 'asc') :?>
                    selected="selected"
                <?php endif; ?> ><?php echo __('Price (Low - High)'); ?></option>
		<option value="<?php echo __('news_from_date&product_list_dir=desc'); ?>" 
			<?php if ($this->getRequest()->getParam('product_list_order') == 'news_from_date' && $block->getCurrentDirection() == 'desc' ) :?>
                    selected="selected"
                <?php endif; ?> ><?php echo __('New Arrivals'); ?></option>
		<option value="<?php echo __('special_price&product_list_dir=desc'); ?>" 
			<?php if ($this->getRequest()->getParam('product_list_order') == 'special_price' && $block->getCurrentDirection() == 'desc') :?>
                    selected="selected"
                <?php endif; ?> ><?php echo __('Offers'); ?></option>
		<option value="<?php echo __('featured&product_list_dir=desc'); ?>" 
			<?php if ($this->getRequest()->getParam('product_list_order') == 'featured' && $block->getCurrentDirection() == 'desc') :?>
                    selected="selected"
                <?php endif; ?> ><?php echo __('Featured'); ?></option>
    </select>
    <?php if ($block->getCurrentDirection() == 'desc') :?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Ascending Direction')) ?>"
           href="#"
           class="action sorter-action sort-desc"
           data-role="direction-switcher"
           data-value="asc" style="display: none;">
            <span><?= $block->escapeHtml(__('Set Ascending Direction')) ?></span>
        </a>
    <?php else :?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Descending Direction')) ?>"
           href="#"
           class="action sorter-action sort-asc"
           data-role="direction-switcher"
           data-value="desc" style="display: none;">
            <span><?= $block->escapeHtml(__('Set Descending Direction')) ?></span>
        </a>
    <?php endif; ?>
</div>
